### PR TITLE
PR for playlist

### PR DESCRIPTION
**Pull request by narharikale**
following features added :
create new playlist
add video to playlist
remove video from playlist

### CODE REVIEW

**Review by prathmeshjagtap — APPROVED** [review]
The code is Clean and Also good structured I liked that you have made different files for each function

**Review by SanjayJatti — APPROVED** [review]
- good use of services
- code is clean

**Review by ayush65 — APPROVED** [review]
Code looks clean 
ClassNames are self explanatory

**Review by preethasri — COMMENTED** [review]
Good to merge 👍

**Pull request merged**
